### PR TITLE
Fixing casing..

### PR DESCRIPTION
**Pull request by elmobp**
You should really fix this bug though! Seems odd to have two fields cased like this

### CODE REVIEW

**Comment by HumanistSerif** [comment]
@elmobp Thanks for the feedback. The casing inconsistency had been fixed prior to the rollout of this new API Doc format, which is why the two fields are lowercased. Are you seeing errors when using `state` and `country`?

**Comment by elmobp** [comment]
Eh? no one told us that its been fixed Ill play around later today and let you know :) in which case this PR should be the opposite heh?

**Comment by elmobp** [comment]
@HumanistSerif  yeh still not fixed, State needs to be cased still country is fine. If I make State all lower case it tells me State can't be blank then change casing to State and it works :)

**Comment by idonovan-cht** [comment]
Hi @elmobp, I'm the one who last worked on the Partner Customer API.

I had held off on notifying people about these changes due to a couple minor concerns brought up post-deployment that I wanted to address first. I would be happy to help resolve your problem!
Do you think that you could provide the following:
1.  The `address` property of your rejected request. I should only need the state and country fields inside of it.
2. The route (HTTP method + URL) of your rejected request.

**Comment by elmobp** [comment]
@idonovan-cht heres the request body
```json
{
  "name": "xxxxx",
  "classification": "managed_with_access",
  "billing_contact": "xxxx",
  "partner_billing_configuration": {
    "enabled": true
  },
  "address": {
    "street1": "xxxx",
    "city": null,
    "State": "xxxx",
    "zipcode": "xxxx",
    "country": "xxx"
  }
}
```
Heres the curl example
```bash
curl -X POST "https://chapi.cloudhealthtech.com/v1/customers?api_key=xxx" -H "Content-type: application/json" -H 'Accept: application/json' -d ...
```

**Comment by idonovan-cht** [comment]
@elmobp Running the query using the casing provided returned the default state value of `MA`, regardless of input. Since our API is case-sensitive this is probably the API thinking capitalized `State` is a completely separate attribute.
```
"address": {
  "street1": "xxx",
  "city": "xxx",
  "state": "MA",
  "zipcode": "xxx",
  "country": "xxx"
}
```
What I think happened: when using the lowercase `state`, our API was unable to map the given string to a state record in our database, so returned an error when validating. Alternatively, if we were unable to parse the country, then the state would not populate as a result and throw an error as well.

What string value were you trying to pass to `state` and `country` when it failed?

**Comment by elmobp** [comment]
state is WA country is Australia.That makes no sense why one would work like that though? It sounds to me like your mapping JSON fields directly to column's in sql

**Comment by idonovan-cht** [comment]
Our backend is Rails, with some other frameworks handling requests. One of those is a decorator pattern that assigns request data to a Customer object before committing it to our ORM. When I said mapping, I may have oversimplified. That library unfortunately conforms to the JSON spec (which is case-sensitive), hence the issue.

I checked our table of states that the API uses. Looking at Australia specifically, we aren't using standard abbreviations, which is why we don't recognize "WA". I'm advocating a ticket internally to fix this annoyance. For the time being, the easiest workaround for your team would be to use the full name of the state - in your case "Western Australia" - just as you do with the country.

```
State Abbreviations in our DB:
Australian Capital Territory = 01
New South Wales = 02
Northern Territory = 03
Queensland = 04
South Australia = 05
Tasmania = 06
Victoria = 07
Western Australia = 08
```

I intend to advocate the ticket heavily to correct these state codes, and as push some better error messaging. In the meantime, I hope this clears things up!

**Comment by elmobp** [comment]
Will mess around with it today sometime though you may want to fix the API docs up there is still the casing issue in the example and the params say:

state required

State specified in abbreviated form. For example, specify Massachusetts as MA.

**Comment by HumanistSerif** [comment]
Thanks @elmobp. If you're okay with it, I'll close this pull request and add an action item at my end to update the doc.

**Comment by HumanistSerif** [comment]
Closing this PR as the issue was addressed in https://github.com/CloudHealth/cht_api_guide/pull/70.

**Comment by elmobp** [comment]
@HumanistSerif  not fixed? http://apidocs.cloudhealthtech.com/#partner_create-partner-customer example still says State where the doc says state the casing issue is still there?

**Comment by HumanistSerif** [comment]
Thanks for flagging this, @elmobp. I pushed out a fix to the example.

**Pull request closed without merging**
